site_name: Py Mono Repo
repo_url: https://github.com/peterHoburg/py_mono_tools
site_url: https://peterhoburg.github.io/py_mono_tools
nav:
  - Home: index.md
  - Concepts: concepts.md
  - Commands: commands.md


theme:
  language: en
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - search
#  - offline
  - minify:
      minify_html: true


markdown_extensions:
    - mkdocs-click
    - toc:
          permalink: true
