site_name: Py Mono Tools
site_url: https://peterhoburg.github.io/py_mono_tools
repo_url: https://github.com/peterHoburg/py_mono_tools

nav:
  - Home: index.md
  - Concepts: concepts.md
  - CLI Reference: cli.md

theme:
  language: en
  name: material
  features:
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.sections
    - navigation.top
#    - toc.integrate
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search
#  - offline
  - minify:
      minify_html: true

markdown_extensions:
  - attr_list
  - mkdocs-click
  - toc:
      permalink: true

watch:
  - docs
  - mkdocs.yml
  - src
