[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "py_mono_build"
version = "0.1.0"
description = ""
authors = ["Peter Hoburg <peterHoburg@users.noreply.github.com>"]
packages = [
    { include = "py_mono_build", from = "src" }
]

[tool.poetry.scripts]
mono-build = "py_mono_build.main:cli"

[tool.poetry.dependencies]
python = "^3.9"

Jinja2 = "^3"
tomli = "^2"
click = "^8"
black = "^22"


[tool.poetry.dev-dependencies]

