[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "py_mono_build"
version = "0.1.0"
description = ""
authors = ["Peter Hoburg <peterHoburg@users.noreply.github.com>"]
packages = [
    { include = "py_mono_build", from = "src" }
]

[tool.poetry.scripts]
mono-build = "py_mono_build.main:cli"

[tool.poetry.dependencies]
python = "^3.9"

Jinja2 = "^3"
tomli = "^2"
click = "^8"
black = "^22"
isort = "^5"
mypy = "^0.971"
flake8 = "^5.0.4"
pydocstyle = "^6.1.1"
pyflakes = "^2.5.0"
pylint = "^2.15.0"
bandit = "^1.7.4"
pydocstringformatter = "^0.7.2"


[tool.poetry.dev-dependencies]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
combine_as_imports = "True"
force_alphabetical_sort_within_sections = "True"
ensure_newline_before_comments = "True"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
lines_after_imports = 2
