- hosts: all
  become: yes
  vars:
    main_user: "vagrant"
    root_user: root
  pre_tasks:
    - name: update repositories
      become: yes
      become_user: root
      apt: update_cache=yes
      changed_when: False

  tasks:
    # https://python-poetry.org/docs/master/#installing-with-the-official-installer
    - name: Download Poetry install script
      get_url:
        url: https://install.python-poetry.org
        dest: "/home/{{ main_user }}/install-poetry.py"
        mode: '0777'

    - name: Run Poetry install script
      become: yes
      become_user: "{{ main_user }}"
      ansible.builtin.script:
        cmd: "/home/{{ main_user }}/install-poetry.py"
      args:
        creates: /home/{{ main_user }}/.local/bin/poetry
        executable: python3

    - name: Install project using Poetry
      become: yes
      become_user: "{{ main_user }}"
      ansible.builtin.command: /home/{{ main_user }}/.local/bin/poetry install
      args:
        chdir: /example_repos/docker_module

